packages:
  - .
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@firebase/util'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - core-js
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
