
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Client` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Client
 * 
 */
export type ClientModel = runtime.Types.Result.DefaultSelection<Prisma.$ClientPayload>

export type AggregateClient = {
  _count: ClientCountAggregateOutputType | null
  _min: ClientMinAggregateOutputType | null
  _max: ClientMaxAggregateOutputType | null
}

export type ClientMinAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  orgId: string | null
  ownerId: string | null
}

export type ClientMaxAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  orgId: string | null
  ownerId: string | null
}

export type ClientCountAggregateOutputType = {
  id: number
  name: number
  email: number
  orgId: number
  ownerId: number
  _all: number
}


export type ClientMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  orgId?: true
  ownerId?: true
}

export type ClientMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  orgId?: true
  ownerId?: true
}

export type ClientCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  orgId?: true
  ownerId?: true
  _all?: true
}

export type ClientAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Client to aggregate.
   */
  where?: Prisma.ClientWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clients to fetch.
   */
  orderBy?: Prisma.ClientOrderByWithRelationInput | Prisma.ClientOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ClientWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clients.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Clients
  **/
  _count?: true | ClientCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ClientMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ClientMaxAggregateInputType
}

export type GetClientAggregateType<T extends ClientAggregateArgs> = {
      [P in keyof T & keyof AggregateClient]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClient[P]>
    : Prisma.GetScalarType<T[P], AggregateClient[P]>
}




export type ClientGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClientWhereInput
  orderBy?: Prisma.ClientOrderByWithAggregationInput | Prisma.ClientOrderByWithAggregationInput[]
  by: Prisma.ClientScalarFieldEnum[] | Prisma.ClientScalarFieldEnum
  having?: Prisma.ClientScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ClientCountAggregateInputType | true
  _min?: ClientMinAggregateInputType
  _max?: ClientMaxAggregateInputType
}

export type ClientGroupByOutputType = {
  id: string
  name: string
  email: string | null
  orgId: string
  ownerId: string
  _count: ClientCountAggregateOutputType | null
  _min: ClientMinAggregateOutputType | null
  _max: ClientMaxAggregateOutputType | null
}

type GetClientGroupByPayload<T extends ClientGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ClientGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ClientGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ClientGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ClientGroupByOutputType[P]>
      }
    >
  >



export type ClientWhereInput = {
  AND?: Prisma.ClientWhereInput | Prisma.ClientWhereInput[]
  OR?: Prisma.ClientWhereInput[]
  NOT?: Prisma.ClientWhereInput | Prisma.ClientWhereInput[]
  id?: Prisma.StringFilter<"Client"> | string
  name?: Prisma.StringFilter<"Client"> | string
  email?: Prisma.StringNullableFilter<"Client"> | string | null
  orgId?: Prisma.StringFilter<"Client"> | string
  ownerId?: Prisma.StringFilter<"Client"> | string
  org?: Prisma.XOR<Prisma.OrgScalarRelationFilter, Prisma.OrgWhereInput>
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  tasks?: Prisma.TaskListRelationFilter
  media?: Prisma.MediaListRelationFilter
}

export type ClientOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  orgId?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  org?: Prisma.OrgOrderByWithRelationInput
  owner?: Prisma.UserOrderByWithRelationInput
  tasks?: Prisma.TaskOrderByRelationAggregateInput
  media?: Prisma.MediaOrderByRelationAggregateInput
}

export type ClientWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ClientWhereInput | Prisma.ClientWhereInput[]
  OR?: Prisma.ClientWhereInput[]
  NOT?: Prisma.ClientWhereInput | Prisma.ClientWhereInput[]
  name?: Prisma.StringFilter<"Client"> | string
  email?: Prisma.StringNullableFilter<"Client"> | string | null
  orgId?: Prisma.StringFilter<"Client"> | string
  ownerId?: Prisma.StringFilter<"Client"> | string
  org?: Prisma.XOR<Prisma.OrgScalarRelationFilter, Prisma.OrgWhereInput>
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  tasks?: Prisma.TaskListRelationFilter
  media?: Prisma.MediaListRelationFilter
}, "id">

export type ClientOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  orgId?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  _count?: Prisma.ClientCountOrderByAggregateInput
  _max?: Prisma.ClientMaxOrderByAggregateInput
  _min?: Prisma.ClientMinOrderByAggregateInput
}

export type ClientScalarWhereWithAggregatesInput = {
  AND?: Prisma.ClientScalarWhereWithAggregatesInput | Prisma.ClientScalarWhereWithAggregatesInput[]
  OR?: Prisma.ClientScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ClientScalarWhereWithAggregatesInput | Prisma.ClientScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Client"> | string
  name?: Prisma.StringWithAggregatesFilter<"Client"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"Client"> | string | null
  orgId?: Prisma.StringWithAggregatesFilter<"Client"> | string
  ownerId?: Prisma.StringWithAggregatesFilter<"Client"> | string
}

export type ClientCreateInput = {
  id?: string
  name: string
  email?: string | null
  org: Prisma.OrgCreateNestedOneWithoutClientsInput
  owner: Prisma.UserCreateNestedOneWithoutClientsInput
  tasks?: Prisma.TaskCreateNestedManyWithoutClientInput
  media?: Prisma.MediaCreateNestedManyWithoutClientInput
}

export type ClientUncheckedCreateInput = {
  id?: string
  name: string
  email?: string | null
  orgId: string
  ownerId: string
  tasks?: Prisma.TaskUncheckedCreateNestedManyWithoutClientInput
  media?: Prisma.MediaUncheckedCreateNestedManyWithoutClientInput
}

export type ClientUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  org?: Prisma.OrgUpdateOneRequiredWithoutClientsNestedInput
  owner?: Prisma.UserUpdateOneRequiredWithoutClientsNestedInput
  tasks?: Prisma.TaskUpdateManyWithoutClientNestedInput
  media?: Prisma.MediaUpdateManyWithoutClientNestedInput
}

export type ClientUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  tasks?: Prisma.TaskUncheckedUpdateManyWithoutClientNestedInput
  media?: Prisma.MediaUncheckedUpdateManyWithoutClientNestedInput
}

export type ClientCreateManyInput = {
  id?: string
  name: string
  email?: string | null
  orgId: string
  ownerId: string
}

export type ClientUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ClientUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ClientListRelationFilter = {
  every?: Prisma.ClientWhereInput
  some?: Prisma.ClientWhereInput
  none?: Prisma.ClientWhereInput
}

export type ClientOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ClientCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
}

export type ClientMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
}

export type ClientMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  orgId?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
}

export type ClientScalarRelationFilter = {
  is?: Prisma.ClientWhereInput
  isNot?: Prisma.ClientWhereInput
}

export type ClientCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.ClientCreateWithoutOwnerInput, Prisma.ClientUncheckedCreateWithoutOwnerInput> | Prisma.ClientCreateWithoutOwnerInput[] | Prisma.ClientUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.ClientCreateOrConnectWithoutOwnerInput | Prisma.ClientCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.ClientCreateManyOwnerInputEnvelope
  connect?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
}

export type ClientUncheckedCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.ClientCreateWithoutOwnerInput, Prisma.ClientUncheckedCreateWithoutOwnerInput> | Prisma.ClientCreateWithoutOwnerInput[] | Prisma.ClientUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.ClientCreateOrConnectWithoutOwnerInput | Prisma.ClientCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.ClientCreateManyOwnerInputEnvelope
  connect?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
}

export type ClientUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.ClientCreateWithoutOwnerInput, Prisma.ClientUncheckedCreateWithoutOwnerInput> | Prisma.ClientCreateWithoutOwnerInput[] | Prisma.ClientUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.ClientCreateOrConnectWithoutOwnerInput | Prisma.ClientCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.ClientUpsertWithWhereUniqueWithoutOwnerInput | Prisma.ClientUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.ClientCreateManyOwnerInputEnvelope
  set?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  disconnect?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  delete?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  connect?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  update?: Prisma.ClientUpdateWithWhereUniqueWithoutOwnerInput | Prisma.ClientUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.ClientUpdateManyWithWhereWithoutOwnerInput | Prisma.ClientUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.ClientScalarWhereInput | Prisma.ClientScalarWhereInput[]
}

export type ClientUncheckedUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.ClientCreateWithoutOwnerInput, Prisma.ClientUncheckedCreateWithoutOwnerInput> | Prisma.ClientCreateWithoutOwnerInput[] | Prisma.ClientUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.ClientCreateOrConnectWithoutOwnerInput | Prisma.ClientCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.ClientUpsertWithWhereUniqueWithoutOwnerInput | Prisma.ClientUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.ClientCreateManyOwnerInputEnvelope
  set?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  disconnect?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  delete?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  connect?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  update?: Prisma.ClientUpdateWithWhereUniqueWithoutOwnerInput | Prisma.ClientUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.ClientUpdateManyWithWhereWithoutOwnerInput | Prisma.ClientUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.ClientScalarWhereInput | Prisma.ClientScalarWhereInput[]
}

export type ClientCreateNestedManyWithoutOrgInput = {
  create?: Prisma.XOR<Prisma.ClientCreateWithoutOrgInput, Prisma.ClientUncheckedCreateWithoutOrgInput> | Prisma.ClientCreateWithoutOrgInput[] | Prisma.ClientUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.ClientCreateOrConnectWithoutOrgInput | Prisma.ClientCreateOrConnectWithoutOrgInput[]
  createMany?: Prisma.ClientCreateManyOrgInputEnvelope
  connect?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
}

export type ClientUncheckedCreateNestedManyWithoutOrgInput = {
  create?: Prisma.XOR<Prisma.ClientCreateWithoutOrgInput, Prisma.ClientUncheckedCreateWithoutOrgInput> | Prisma.ClientCreateWithoutOrgInput[] | Prisma.ClientUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.ClientCreateOrConnectWithoutOrgInput | Prisma.ClientCreateOrConnectWithoutOrgInput[]
  createMany?: Prisma.ClientCreateManyOrgInputEnvelope
  connect?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
}

export type ClientUpdateManyWithoutOrgNestedInput = {
  create?: Prisma.XOR<Prisma.ClientCreateWithoutOrgInput, Prisma.ClientUncheckedCreateWithoutOrgInput> | Prisma.ClientCreateWithoutOrgInput[] | Prisma.ClientUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.ClientCreateOrConnectWithoutOrgInput | Prisma.ClientCreateOrConnectWithoutOrgInput[]
  upsert?: Prisma.ClientUpsertWithWhereUniqueWithoutOrgInput | Prisma.ClientUpsertWithWhereUniqueWithoutOrgInput[]
  createMany?: Prisma.ClientCreateManyOrgInputEnvelope
  set?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  disconnect?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  delete?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  connect?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  update?: Prisma.ClientUpdateWithWhereUniqueWithoutOrgInput | Prisma.ClientUpdateWithWhereUniqueWithoutOrgInput[]
  updateMany?: Prisma.ClientUpdateManyWithWhereWithoutOrgInput | Prisma.ClientUpdateManyWithWhereWithoutOrgInput[]
  deleteMany?: Prisma.ClientScalarWhereInput | Prisma.ClientScalarWhereInput[]
}

export type ClientUncheckedUpdateManyWithoutOrgNestedInput = {
  create?: Prisma.XOR<Prisma.ClientCreateWithoutOrgInput, Prisma.ClientUncheckedCreateWithoutOrgInput> | Prisma.ClientCreateWithoutOrgInput[] | Prisma.ClientUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.ClientCreateOrConnectWithoutOrgInput | Prisma.ClientCreateOrConnectWithoutOrgInput[]
  upsert?: Prisma.ClientUpsertWithWhereUniqueWithoutOrgInput | Prisma.ClientUpsertWithWhereUniqueWithoutOrgInput[]
  createMany?: Prisma.ClientCreateManyOrgInputEnvelope
  set?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  disconnect?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  delete?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  connect?: Prisma.ClientWhereUniqueInput | Prisma.ClientWhereUniqueInput[]
  update?: Prisma.ClientUpdateWithWhereUniqueWithoutOrgInput | Prisma.ClientUpdateWithWhereUniqueWithoutOrgInput[]
  updateMany?: Prisma.ClientUpdateManyWithWhereWithoutOrgInput | Prisma.ClientUpdateManyWithWhereWithoutOrgInput[]
  deleteMany?: Prisma.ClientScalarWhereInput | Prisma.ClientScalarWhereInput[]
}

export type ClientCreateNestedOneWithoutTasksInput = {
  create?: Prisma.XOR<Prisma.ClientCreateWithoutTasksInput, Prisma.ClientUncheckedCreateWithoutTasksInput>
  connectOrCreate?: Prisma.ClientCreateOrConnectWithoutTasksInput
  connect?: Prisma.ClientWhereUniqueInput
}

export type ClientUpdateOneRequiredWithoutTasksNestedInput = {
  create?: Prisma.XOR<Prisma.ClientCreateWithoutTasksInput, Prisma.ClientUncheckedCreateWithoutTasksInput>
  connectOrCreate?: Prisma.ClientCreateOrConnectWithoutTasksInput
  upsert?: Prisma.ClientUpsertWithoutTasksInput
  connect?: Prisma.ClientWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClientUpdateToOneWithWhereWithoutTasksInput, Prisma.ClientUpdateWithoutTasksInput>, Prisma.ClientUncheckedUpdateWithoutTasksInput>
}

export type ClientCreateNestedOneWithoutMediaInput = {
  create?: Prisma.XOR<Prisma.ClientCreateWithoutMediaInput, Prisma.ClientUncheckedCreateWithoutMediaInput>
  connectOrCreate?: Prisma.ClientCreateOrConnectWithoutMediaInput
  connect?: Prisma.ClientWhereUniqueInput
}

export type ClientUpdateOneRequiredWithoutMediaNestedInput = {
  create?: Prisma.XOR<Prisma.ClientCreateWithoutMediaInput, Prisma.ClientUncheckedCreateWithoutMediaInput>
  connectOrCreate?: Prisma.ClientCreateOrConnectWithoutMediaInput
  upsert?: Prisma.ClientUpsertWithoutMediaInput
  connect?: Prisma.ClientWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClientUpdateToOneWithWhereWithoutMediaInput, Prisma.ClientUpdateWithoutMediaInput>, Prisma.ClientUncheckedUpdateWithoutMediaInput>
}

export type ClientCreateWithoutOwnerInput = {
  id?: string
  name: string
  email?: string | null
  org: Prisma.OrgCreateNestedOneWithoutClientsInput
  tasks?: Prisma.TaskCreateNestedManyWithoutClientInput
  media?: Prisma.MediaCreateNestedManyWithoutClientInput
}

export type ClientUncheckedCreateWithoutOwnerInput = {
  id?: string
  name: string
  email?: string | null
  orgId: string
  tasks?: Prisma.TaskUncheckedCreateNestedManyWithoutClientInput
  media?: Prisma.MediaUncheckedCreateNestedManyWithoutClientInput
}

export type ClientCreateOrConnectWithoutOwnerInput = {
  where: Prisma.ClientWhereUniqueInput
  create: Prisma.XOR<Prisma.ClientCreateWithoutOwnerInput, Prisma.ClientUncheckedCreateWithoutOwnerInput>
}

export type ClientCreateManyOwnerInputEnvelope = {
  data: Prisma.ClientCreateManyOwnerInput | Prisma.ClientCreateManyOwnerInput[]
  skipDuplicates?: boolean
}

export type ClientUpsertWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.ClientWhereUniqueInput
  update: Prisma.XOR<Prisma.ClientUpdateWithoutOwnerInput, Prisma.ClientUncheckedUpdateWithoutOwnerInput>
  create: Prisma.XOR<Prisma.ClientCreateWithoutOwnerInput, Prisma.ClientUncheckedCreateWithoutOwnerInput>
}

export type ClientUpdateWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.ClientWhereUniqueInput
  data: Prisma.XOR<Prisma.ClientUpdateWithoutOwnerInput, Prisma.ClientUncheckedUpdateWithoutOwnerInput>
}

export type ClientUpdateManyWithWhereWithoutOwnerInput = {
  where: Prisma.ClientScalarWhereInput
  data: Prisma.XOR<Prisma.ClientUpdateManyMutationInput, Prisma.ClientUncheckedUpdateManyWithoutOwnerInput>
}

export type ClientScalarWhereInput = {
  AND?: Prisma.ClientScalarWhereInput | Prisma.ClientScalarWhereInput[]
  OR?: Prisma.ClientScalarWhereInput[]
  NOT?: Prisma.ClientScalarWhereInput | Prisma.ClientScalarWhereInput[]
  id?: Prisma.StringFilter<"Client"> | string
  name?: Prisma.StringFilter<"Client"> | string
  email?: Prisma.StringNullableFilter<"Client"> | string | null
  orgId?: Prisma.StringFilter<"Client"> | string
  ownerId?: Prisma.StringFilter<"Client"> | string
}

export type ClientCreateWithoutOrgInput = {
  id?: string
  name: string
  email?: string | null
  owner: Prisma.UserCreateNestedOneWithoutClientsInput
  tasks?: Prisma.TaskCreateNestedManyWithoutClientInput
  media?: Prisma.MediaCreateNestedManyWithoutClientInput
}

export type ClientUncheckedCreateWithoutOrgInput = {
  id?: string
  name: string
  email?: string | null
  ownerId: string
  tasks?: Prisma.TaskUncheckedCreateNestedManyWithoutClientInput
  media?: Prisma.MediaUncheckedCreateNestedManyWithoutClientInput
}

export type ClientCreateOrConnectWithoutOrgInput = {
  where: Prisma.ClientWhereUniqueInput
  create: Prisma.XOR<Prisma.ClientCreateWithoutOrgInput, Prisma.ClientUncheckedCreateWithoutOrgInput>
}

export type ClientCreateManyOrgInputEnvelope = {
  data: Prisma.ClientCreateManyOrgInput | Prisma.ClientCreateManyOrgInput[]
  skipDuplicates?: boolean
}

export type ClientUpsertWithWhereUniqueWithoutOrgInput = {
  where: Prisma.ClientWhereUniqueInput
  update: Prisma.XOR<Prisma.ClientUpdateWithoutOrgInput, Prisma.ClientUncheckedUpdateWithoutOrgInput>
  create: Prisma.XOR<Prisma.ClientCreateWithoutOrgInput, Prisma.ClientUncheckedCreateWithoutOrgInput>
}

export type ClientUpdateWithWhereUniqueWithoutOrgInput = {
  where: Prisma.ClientWhereUniqueInput
  data: Prisma.XOR<Prisma.ClientUpdateWithoutOrgInput, Prisma.ClientUncheckedUpdateWithoutOrgInput>
}

export type ClientUpdateManyWithWhereWithoutOrgInput = {
  where: Prisma.ClientScalarWhereInput
  data: Prisma.XOR<Prisma.ClientUpdateManyMutationInput, Prisma.ClientUncheckedUpdateManyWithoutOrgInput>
}

export type ClientCreateWithoutTasksInput = {
  id?: string
  name: string
  email?: string | null
  org: Prisma.OrgCreateNestedOneWithoutClientsInput
  owner: Prisma.UserCreateNestedOneWithoutClientsInput
  media?: Prisma.MediaCreateNestedManyWithoutClientInput
}

export type ClientUncheckedCreateWithoutTasksInput = {
  id?: string
  name: string
  email?: string | null
  orgId: string
  ownerId: string
  media?: Prisma.MediaUncheckedCreateNestedManyWithoutClientInput
}

export type ClientCreateOrConnectWithoutTasksInput = {
  where: Prisma.ClientWhereUniqueInput
  create: Prisma.XOR<Prisma.ClientCreateWithoutTasksInput, Prisma.ClientUncheckedCreateWithoutTasksInput>
}

export type ClientUpsertWithoutTasksInput = {
  update: Prisma.XOR<Prisma.ClientUpdateWithoutTasksInput, Prisma.ClientUncheckedUpdateWithoutTasksInput>
  create: Prisma.XOR<Prisma.ClientCreateWithoutTasksInput, Prisma.ClientUncheckedCreateWithoutTasksInput>
  where?: Prisma.ClientWhereInput
}

export type ClientUpdateToOneWithWhereWithoutTasksInput = {
  where?: Prisma.ClientWhereInput
  data: Prisma.XOR<Prisma.ClientUpdateWithoutTasksInput, Prisma.ClientUncheckedUpdateWithoutTasksInput>
}

export type ClientUpdateWithoutTasksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  org?: Prisma.OrgUpdateOneRequiredWithoutClientsNestedInput
  owner?: Prisma.UserUpdateOneRequiredWithoutClientsNestedInput
  media?: Prisma.MediaUpdateManyWithoutClientNestedInput
}

export type ClientUncheckedUpdateWithoutTasksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  media?: Prisma.MediaUncheckedUpdateManyWithoutClientNestedInput
}

export type ClientCreateWithoutMediaInput = {
  id?: string
  name: string
  email?: string | null
  org: Prisma.OrgCreateNestedOneWithoutClientsInput
  owner: Prisma.UserCreateNestedOneWithoutClientsInput
  tasks?: Prisma.TaskCreateNestedManyWithoutClientInput
}

export type ClientUncheckedCreateWithoutMediaInput = {
  id?: string
  name: string
  email?: string | null
  orgId: string
  ownerId: string
  tasks?: Prisma.TaskUncheckedCreateNestedManyWithoutClientInput
}

export type ClientCreateOrConnectWithoutMediaInput = {
  where: Prisma.ClientWhereUniqueInput
  create: Prisma.XOR<Prisma.ClientCreateWithoutMediaInput, Prisma.ClientUncheckedCreateWithoutMediaInput>
}

export type ClientUpsertWithoutMediaInput = {
  update: Prisma.XOR<Prisma.ClientUpdateWithoutMediaInput, Prisma.ClientUncheckedUpdateWithoutMediaInput>
  create: Prisma.XOR<Prisma.ClientCreateWithoutMediaInput, Prisma.ClientUncheckedCreateWithoutMediaInput>
  where?: Prisma.ClientWhereInput
}

export type ClientUpdateToOneWithWhereWithoutMediaInput = {
  where?: Prisma.ClientWhereInput
  data: Prisma.XOR<Prisma.ClientUpdateWithoutMediaInput, Prisma.ClientUncheckedUpdateWithoutMediaInput>
}

export type ClientUpdateWithoutMediaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  org?: Prisma.OrgUpdateOneRequiredWithoutClientsNestedInput
  owner?: Prisma.UserUpdateOneRequiredWithoutClientsNestedInput
  tasks?: Prisma.TaskUpdateManyWithoutClientNestedInput
}

export type ClientUncheckedUpdateWithoutMediaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  tasks?: Prisma.TaskUncheckedUpdateManyWithoutClientNestedInput
}

export type ClientCreateManyOwnerInput = {
  id?: string
  name: string
  email?: string | null
  orgId: string
}

export type ClientUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  org?: Prisma.OrgUpdateOneRequiredWithoutClientsNestedInput
  tasks?: Prisma.TaskUpdateManyWithoutClientNestedInput
  media?: Prisma.MediaUpdateManyWithoutClientNestedInput
}

export type ClientUncheckedUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  tasks?: Prisma.TaskUncheckedUpdateManyWithoutClientNestedInput
  media?: Prisma.MediaUncheckedUpdateManyWithoutClientNestedInput
}

export type ClientUncheckedUpdateManyWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ClientCreateManyOrgInput = {
  id?: string
  name: string
  email?: string | null
  ownerId: string
}

export type ClientUpdateWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  owner?: Prisma.UserUpdateOneRequiredWithoutClientsNestedInput
  tasks?: Prisma.TaskUpdateManyWithoutClientNestedInput
  media?: Prisma.MediaUpdateManyWithoutClientNestedInput
}

export type ClientUncheckedUpdateWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  tasks?: Prisma.TaskUncheckedUpdateManyWithoutClientNestedInput
  media?: Prisma.MediaUncheckedUpdateManyWithoutClientNestedInput
}

export type ClientUncheckedUpdateManyWithoutOrgInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type ClientCountOutputType
 */

export type ClientCountOutputType = {
  tasks: number
  media: number
}

export type ClientCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tasks?: boolean | ClientCountOutputTypeCountTasksArgs
  media?: boolean | ClientCountOutputTypeCountMediaArgs
}

/**
 * ClientCountOutputType without action
 */
export type ClientCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientCountOutputType
   */
  select?: Prisma.ClientCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ClientCountOutputType without action
 */
export type ClientCountOutputTypeCountTasksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TaskWhereInput
}

/**
 * ClientCountOutputType without action
 */
export type ClientCountOutputTypeCountMediaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MediaWhereInput
}


export type ClientSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  orgId?: boolean
  ownerId?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  tasks?: boolean | Prisma.Client$tasksArgs<ExtArgs>
  media?: boolean | Prisma.Client$mediaArgs<ExtArgs>
  _count?: boolean | Prisma.ClientCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["client"]>

export type ClientSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  orgId?: boolean
  ownerId?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["client"]>

export type ClientSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  orgId?: boolean
  ownerId?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["client"]>

export type ClientSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  orgId?: boolean
  ownerId?: boolean
}

export type ClientOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "orgId" | "ownerId", ExtArgs["result"]["client"]>
export type ClientInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  tasks?: boolean | Prisma.Client$tasksArgs<ExtArgs>
  media?: boolean | Prisma.Client$mediaArgs<ExtArgs>
  _count?: boolean | Prisma.ClientCountOutputTypeDefaultArgs<ExtArgs>
}
export type ClientIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ClientIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ClientPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Client"
  objects: {
    org: Prisma.$OrgPayload<ExtArgs>
    owner: Prisma.$UserPayload<ExtArgs>
    tasks: Prisma.$TaskPayload<ExtArgs>[]
    media: Prisma.$MediaPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    email: string | null
    orgId: string
    ownerId: string
  }, ExtArgs["result"]["client"]>
  composites: {}
}

export type ClientGetPayload<S extends boolean | null | undefined | ClientDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ClientPayload, S>

export type ClientCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ClientFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ClientCountAggregateInputType | true
  }

export interface ClientDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Client'], meta: { name: 'Client' } }
  /**
   * Find zero or one Client that matches the filter.
   * @param {ClientFindUniqueArgs} args - Arguments to find a Client
   * @example
   * // Get one Client
   * const client = await prisma.client.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ClientFindUniqueArgs>(args: Prisma.SelectSubset<T, ClientFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ClientClient<runtime.Types.Result.GetResult<Prisma.$ClientPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Client that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ClientFindUniqueOrThrowArgs} args - Arguments to find a Client
   * @example
   * // Get one Client
   * const client = await prisma.client.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ClientFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ClientFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClientClient<runtime.Types.Result.GetResult<Prisma.$ClientPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Client that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientFindFirstArgs} args - Arguments to find a Client
   * @example
   * // Get one Client
   * const client = await prisma.client.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ClientFindFirstArgs>(args?: Prisma.SelectSubset<T, ClientFindFirstArgs<ExtArgs>>): Prisma.Prisma__ClientClient<runtime.Types.Result.GetResult<Prisma.$ClientPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Client that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientFindFirstOrThrowArgs} args - Arguments to find a Client
   * @example
   * // Get one Client
   * const client = await prisma.client.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ClientFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ClientFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClientClient<runtime.Types.Result.GetResult<Prisma.$ClientPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Clients that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Clients
   * const clients = await prisma.client.findMany()
   * 
   * // Get first 10 Clients
   * const clients = await prisma.client.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const clientWithIdOnly = await prisma.client.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ClientFindManyArgs>(args?: Prisma.SelectSubset<T, ClientFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Client.
   * @param {ClientCreateArgs} args - Arguments to create a Client.
   * @example
   * // Create one Client
   * const Client = await prisma.client.create({
   *   data: {
   *     // ... data to create a Client
   *   }
   * })
   * 
   */
  create<T extends ClientCreateArgs>(args: Prisma.SelectSubset<T, ClientCreateArgs<ExtArgs>>): Prisma.Prisma__ClientClient<runtime.Types.Result.GetResult<Prisma.$ClientPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Clients.
   * @param {ClientCreateManyArgs} args - Arguments to create many Clients.
   * @example
   * // Create many Clients
   * const client = await prisma.client.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ClientCreateManyArgs>(args?: Prisma.SelectSubset<T, ClientCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Clients and returns the data saved in the database.
   * @param {ClientCreateManyAndReturnArgs} args - Arguments to create many Clients.
   * @example
   * // Create many Clients
   * const client = await prisma.client.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Clients and only return the `id`
   * const clientWithIdOnly = await prisma.client.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ClientCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ClientCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Client.
   * @param {ClientDeleteArgs} args - Arguments to delete one Client.
   * @example
   * // Delete one Client
   * const Client = await prisma.client.delete({
   *   where: {
   *     // ... filter to delete one Client
   *   }
   * })
   * 
   */
  delete<T extends ClientDeleteArgs>(args: Prisma.SelectSubset<T, ClientDeleteArgs<ExtArgs>>): Prisma.Prisma__ClientClient<runtime.Types.Result.GetResult<Prisma.$ClientPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Client.
   * @param {ClientUpdateArgs} args - Arguments to update one Client.
   * @example
   * // Update one Client
   * const client = await prisma.client.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ClientUpdateArgs>(args: Prisma.SelectSubset<T, ClientUpdateArgs<ExtArgs>>): Prisma.Prisma__ClientClient<runtime.Types.Result.GetResult<Prisma.$ClientPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Clients.
   * @param {ClientDeleteManyArgs} args - Arguments to filter Clients to delete.
   * @example
   * // Delete a few Clients
   * const { count } = await prisma.client.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ClientDeleteManyArgs>(args?: Prisma.SelectSubset<T, ClientDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Clients.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Clients
   * const client = await prisma.client.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ClientUpdateManyArgs>(args: Prisma.SelectSubset<T, ClientUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Clients and returns the data updated in the database.
   * @param {ClientUpdateManyAndReturnArgs} args - Arguments to update many Clients.
   * @example
   * // Update many Clients
   * const client = await prisma.client.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Clients and only return the `id`
   * const clientWithIdOnly = await prisma.client.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ClientUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ClientUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Client.
   * @param {ClientUpsertArgs} args - Arguments to update or create a Client.
   * @example
   * // Update or create a Client
   * const client = await prisma.client.upsert({
   *   create: {
   *     // ... data to create a Client
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Client we want to update
   *   }
   * })
   */
  upsert<T extends ClientUpsertArgs>(args: Prisma.SelectSubset<T, ClientUpsertArgs<ExtArgs>>): Prisma.Prisma__ClientClient<runtime.Types.Result.GetResult<Prisma.$ClientPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Clients.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientCountArgs} args - Arguments to filter Clients to count.
   * @example
   * // Count the number of Clients
   * const count = await prisma.client.count({
   *   where: {
   *     // ... the filter for the Clients we want to count
   *   }
   * })
  **/
  count<T extends ClientCountArgs>(
    args?: Prisma.Subset<T, ClientCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ClientCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Client.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ClientAggregateArgs>(args: Prisma.Subset<T, ClientAggregateArgs>): Prisma.PrismaPromise<GetClientAggregateType<T>>

  /**
   * Group by Client.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ClientGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ClientGroupByArgs['orderBy'] }
      : { orderBy?: ClientGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ClientGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetClientGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Client model
 */
readonly fields: ClientFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Client.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ClientClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  org<T extends Prisma.OrgDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrgDefaultArgs<ExtArgs>>): Prisma.Prisma__OrgClient<runtime.Types.Result.GetResult<Prisma.$OrgPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  owner<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  tasks<T extends Prisma.Client$tasksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Client$tasksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  media<T extends Prisma.Client$mediaArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Client$mediaArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Client model
 */
export interface ClientFieldRefs {
  readonly id: Prisma.FieldRef<"Client", 'String'>
  readonly name: Prisma.FieldRef<"Client", 'String'>
  readonly email: Prisma.FieldRef<"Client", 'String'>
  readonly orgId: Prisma.FieldRef<"Client", 'String'>
  readonly ownerId: Prisma.FieldRef<"Client", 'String'>
}
    

// Custom InputTypes
/**
 * Client findUnique
 */
export type ClientFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Client
   */
  select?: Prisma.ClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Client
   */
  omit?: Prisma.ClientOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientInclude<ExtArgs> | null
  /**
   * Filter, which Client to fetch.
   */
  where: Prisma.ClientWhereUniqueInput
}

/**
 * Client findUniqueOrThrow
 */
export type ClientFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Client
   */
  select?: Prisma.ClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Client
   */
  omit?: Prisma.ClientOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientInclude<ExtArgs> | null
  /**
   * Filter, which Client to fetch.
   */
  where: Prisma.ClientWhereUniqueInput
}

/**
 * Client findFirst
 */
export type ClientFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Client
   */
  select?: Prisma.ClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Client
   */
  omit?: Prisma.ClientOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientInclude<ExtArgs> | null
  /**
   * Filter, which Client to fetch.
   */
  where?: Prisma.ClientWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clients to fetch.
   */
  orderBy?: Prisma.ClientOrderByWithRelationInput | Prisma.ClientOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Clients.
   */
  cursor?: Prisma.ClientWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clients.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Clients.
   */
  distinct?: Prisma.ClientScalarFieldEnum | Prisma.ClientScalarFieldEnum[]
}

/**
 * Client findFirstOrThrow
 */
export type ClientFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Client
   */
  select?: Prisma.ClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Client
   */
  omit?: Prisma.ClientOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientInclude<ExtArgs> | null
  /**
   * Filter, which Client to fetch.
   */
  where?: Prisma.ClientWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clients to fetch.
   */
  orderBy?: Prisma.ClientOrderByWithRelationInput | Prisma.ClientOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Clients.
   */
  cursor?: Prisma.ClientWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clients.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Clients.
   */
  distinct?: Prisma.ClientScalarFieldEnum | Prisma.ClientScalarFieldEnum[]
}

/**
 * Client findMany
 */
export type ClientFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Client
   */
  select?: Prisma.ClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Client
   */
  omit?: Prisma.ClientOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientInclude<ExtArgs> | null
  /**
   * Filter, which Clients to fetch.
   */
  where?: Prisma.ClientWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clients to fetch.
   */
  orderBy?: Prisma.ClientOrderByWithRelationInput | Prisma.ClientOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Clients.
   */
  cursor?: Prisma.ClientWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clients.
   */
  skip?: number
  distinct?: Prisma.ClientScalarFieldEnum | Prisma.ClientScalarFieldEnum[]
}

/**
 * Client create
 */
export type ClientCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Client
   */
  select?: Prisma.ClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Client
   */
  omit?: Prisma.ClientOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientInclude<ExtArgs> | null
  /**
   * The data needed to create a Client.
   */
  data: Prisma.XOR<Prisma.ClientCreateInput, Prisma.ClientUncheckedCreateInput>
}

/**
 * Client createMany
 */
export type ClientCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Clients.
   */
  data: Prisma.ClientCreateManyInput | Prisma.ClientCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Client createManyAndReturn
 */
export type ClientCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Client
   */
  select?: Prisma.ClientSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Client
   */
  omit?: Prisma.ClientOmit<ExtArgs> | null
  /**
   * The data used to create many Clients.
   */
  data: Prisma.ClientCreateManyInput | Prisma.ClientCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Client update
 */
export type ClientUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Client
   */
  select?: Prisma.ClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Client
   */
  omit?: Prisma.ClientOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientInclude<ExtArgs> | null
  /**
   * The data needed to update a Client.
   */
  data: Prisma.XOR<Prisma.ClientUpdateInput, Prisma.ClientUncheckedUpdateInput>
  /**
   * Choose, which Client to update.
   */
  where: Prisma.ClientWhereUniqueInput
}

/**
 * Client updateMany
 */
export type ClientUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Clients.
   */
  data: Prisma.XOR<Prisma.ClientUpdateManyMutationInput, Prisma.ClientUncheckedUpdateManyInput>
  /**
   * Filter which Clients to update
   */
  where?: Prisma.ClientWhereInput
  /**
   * Limit how many Clients to update.
   */
  limit?: number
}

/**
 * Client updateManyAndReturn
 */
export type ClientUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Client
   */
  select?: Prisma.ClientSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Client
   */
  omit?: Prisma.ClientOmit<ExtArgs> | null
  /**
   * The data used to update Clients.
   */
  data: Prisma.XOR<Prisma.ClientUpdateManyMutationInput, Prisma.ClientUncheckedUpdateManyInput>
  /**
   * Filter which Clients to update
   */
  where?: Prisma.ClientWhereInput
  /**
   * Limit how many Clients to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Client upsert
 */
export type ClientUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Client
   */
  select?: Prisma.ClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Client
   */
  omit?: Prisma.ClientOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientInclude<ExtArgs> | null
  /**
   * The filter to search for the Client to update in case it exists.
   */
  where: Prisma.ClientWhereUniqueInput
  /**
   * In case the Client found by the `where` argument doesn't exist, create a new Client with this data.
   */
  create: Prisma.XOR<Prisma.ClientCreateInput, Prisma.ClientUncheckedCreateInput>
  /**
   * In case the Client was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ClientUpdateInput, Prisma.ClientUncheckedUpdateInput>
}

/**
 * Client delete
 */
export type ClientDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Client
   */
  select?: Prisma.ClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Client
   */
  omit?: Prisma.ClientOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientInclude<ExtArgs> | null
  /**
   * Filter which Client to delete.
   */
  where: Prisma.ClientWhereUniqueInput
}

/**
 * Client deleteMany
 */
export type ClientDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Clients to delete
   */
  where?: Prisma.ClientWhereInput
  /**
   * Limit how many Clients to delete.
   */
  limit?: number
}

/**
 * Client.tasks
 */
export type Client$tasksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
  where?: Prisma.TaskWhereInput
  orderBy?: Prisma.TaskOrderByWithRelationInput | Prisma.TaskOrderByWithRelationInput[]
  cursor?: Prisma.TaskWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TaskScalarFieldEnum | Prisma.TaskScalarFieldEnum[]
}

/**
 * Client.media
 */
export type Client$mediaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Media
   */
  select?: Prisma.MediaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Media
   */
  omit?: Prisma.MediaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MediaInclude<ExtArgs> | null
  where?: Prisma.MediaWhereInput
  orderBy?: Prisma.MediaOrderByWithRelationInput | Prisma.MediaOrderByWithRelationInput[]
  cursor?: Prisma.MediaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MediaScalarFieldEnum | Prisma.MediaScalarFieldEnum[]
}

/**
 * Client without action
 */
export type ClientDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Client
   */
  select?: Prisma.ClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Client
   */
  omit?: Prisma.ClientOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientInclude<ExtArgs> | null
}
